/**
 * Kindred spirits: the fourth result shape, for "Which early Christian thinks like you?".
 *
 * The reader agrees or disagrees with 23 plain statements. Each is compared, one at a time, with
 * what 22 early Christians are on record as holding (+2 .. -2, each proved by a line of their own),
 * and the result names two people: the one whose positions sit nearest (the kindred spirit) and the
 * one who would argue (the sparring partner). Nearest by position, never a percentage: the likeness
 * below orders people and is never printed (the quiz sets `hideOutcomeScore`).
 *
 * THIS IS A PORT of design/quiz-ideas/fathers/score.js, the scorer the owner's tap-through ran,
 * with the same numbers (K 3, MIN_SHARED 6, SHRINK 0.5) and the same arithmetic in the same order,
 * so a tie breaks the same way. The engine test re-scores the 30 simulated people of people-test-1
 * through both and fails on any difference. In score.js's own words:
 *
 *   LIKENESS to a person = the sum, over the statements you both take a side on, of (your answer -
 *   SHRINK x the usual answer) x (their position - SHRINK x the usual position among the people),
 *   divided by that count plus K. You are matched on where you lean differently from most people,
 *   and they on where they differed from the others, so a statement nearly everyone agrees with
 *   (a good laugh, tears at a funeral) cannot hand the same person to every player. K keeps a
 *   person you share few statements with from winning on a coincidence.
 *
 *   EVERYONE is ranked, however little you share. Only NAMING needs a floor: the kindred spirit
 *   and the sparring partner must each rest on at least MIN_SHARED answers they actually
 *   addressed. The kindred spirit is the likest such person, except anyone at the opposite end
 *   from you on two statements you both hold strongly. The sparring partner is the least like
 *   you among those you clash with more than you agree with, with at least two real clashes.
 *
 * What the result then SHOWS (which of the kindred spirit's lines, the face-off, the card's line)
 * is chosen here too, as the approved preview (preview/app.js, draft 4) chooses it, so the result
 * page, the share card and the tests all read one choice: see KindredShow in engine/types.ts.
 *
 * THE DATA. This module imports src/data/which-early-christian-scoring.json: statements, the usual
 * answer and position on each, and every person's positions, with no lines in it. It travels to
 * the browser with the registry, so keep it small. The lines, hooks, portraits and pairs are in
 * src/data/which-early-christian.json, which is SERVER ONLY: pages read it in their front matter
 * (see KindredData below for its shape). Never import it from here or from the quiz file.
 * Both are generated by scripts/build-early-christian-data.mjs; never hand-edit either.
 *
 * THE CODE is the 23 answers, one base-5 digit each (0 strongly disagree .. 4 strongly agree, in
 * play order), written in base 36 behind 'EC': thirteen characters. The quiz hands out a six-
 * character short link instead (`shortLinks`, engine/links.ts). A result link rebuilds the whole
 * result, so nothing is kept but what the link already says.
 */
import data from '../../data/which-early-christian-scoring.json';
import { makeCodec } from '../engine/codec';
import type {
  Answer, KindredCell, KindredPerson, KindredShow, KindredView, Quiz, ScoringStrategy, Sheet
} from '../engine/types';

/** The numbers of design/quiz-ideas/fathers/score.js. Change them there and here together. */
export const K = 3;
export const MIN_SHARED = 6;
export const SHRINK = 0.5;

/** How long a line may be and still be the card's first choice (preview/app.js, cardLine). */
const CARD_LINE_MAX = 170;

/** One of the 23 statements, in play order. */
export interface KindredStatement {
  /** 'laugh', 'war': the key everything else uses. Also the quiz group's key. */
  id: string;
  /** The statement as the reader sees it. */
  text: string;
  /** Its topic in lower case, for mid-sentence use: "On laughter", "Face to face on war". */
  topic: string;
  /** Its question page: /early-church-on/<slug>/. Also the quiz group's slug. */
  slug: string;
}

/** A position, in the scoring file: whether its line is shown, and how long that line is. */
interface ScoringCell {
  v: Answer;
  hide?: true;
  len?: number;
}

/** A person, in the scoring file. */
export interface KindredScoringPerson {
  slug: string;
  name: string;
  short: string;
  she: boolean;
  dates: string;
  who: string;
  cells: Record<string, ScoringCell>;
}

interface ScoringData {
  statements: KindredStatement[];
  /** Per statement: [the usual answer among test players, the usual position among the people]. */
  centre: Record<string, [number, number]>;
  /** In the design's order (which breaks ties exactly as score.js does). */
  people: Record<string, KindredScoringPerson>;
}

/*
 * ---- The server-only file's shape (src/data/which-early-christian.json) ----------------------
 *
 * Declared here so every page reads it through one type:
 *
 *   import full from '../data/which-early-christian.json';
 *   import type { KindredData } from '../lib/strategies/kindred';
 *   const EC = full as unknown as KindredData;
 */

/** A position with the words that prove it. */
export interface KindredLine {
  v: Answer;
  /** The work, by one plain name a reader could search for ("City of God", "Letter to Demetrias"). */
  work: string;
  /** Who recorded the words, where the person did not write them down ("as Athanasius recorded his words"). */
  by: string | null;
  /**
   * True when the line is on record but not shown (unclear out of context): it still counts in the
   * matching, and a page prints "On record in <work>" instead of a quotation.
   */
  hide?: true;
  /** The line, verbatim from a public-domain translation, or our own where `own`. Absent when hidden. */
  line?: string;
  /** Our own translation: print "Our translation" after the work. */
  own?: boolean;
  /** A sentence a reader needs to follow the line, printed under it. */
  note?: string | null;
}

export interface KindredPortrait {
  /** /img/early-christians/<slug>.jpg */
  src: string;
  /** /img/early-christians/thumb/<slug>.jpg, 160px wide, for chips and strips. */
  thumb: string;
  width: number;
  height: number;
  /** The whole credit, ready to print under the picture. */
  credit: string;
  /** The Commons file page. */
  page: string;
  license: string;
}

export interface EarlyChristian {
  slug: string;
  name: string;
  short: string;
  she: boolean;
  /** "354 to 430", "c. 347 to 407", "7th century". */
  dates: string;
  /** "North Africa". */
  where: string;
  /** One line on who they were. */
  who: string;
  /** A true story, in at most 35 words. */
  hook: string;
  /** A note a devout reader should not be surprised by later (Tertullian, Origen, Lactantius), or null. */
  status: string | null;
  portrait: KindredPortrait;
  /** A real link to another result, by that person's key: pairs.ambrose on Augustine. */
  pairs: Record<string, string>;
  /** Only the statements this person is on record on, in play order. */
  cells: Record<string, KindredLine>;
}

export interface KindredData {
  statements: KindredStatement[];
  /** Everyone's key, oldest first, as /early-christian/ lists them. */
  oldestFirst: string[];
  people: Record<string, EarlyChristian>;
}

// ---------------------------------------------------------------- the scoring data

export const KINDRED = data as unknown as ScoringData;
/** The 23 statements, in play order. */
export const STATEMENTS = KINDRED.statements;
/** Every person a result can name, by key, in the design's order. */
export const PEOPLE = KINDRED.people;
export const PEOPLE_KEYS = Object.keys(PEOPLE);

/** The statement with this id. */
export const statementOf = (id: string) => STATEMENTS.find(s => s.id === id);

/** The line that says so for this person on this statement is shown, not only on record. */
const shownFor = (key: string) => (x: { id: string }) => {
  const c = PEOPLE[key]?.cells[x.id];
  return Boolean(c && !c.hide);
};

// ---------------------------------------------------------------- the port of score.js

interface Row extends KindredCell {
  raw: number;
  w: number;
}

interface Compared {
  key: string;
  n: number;
  like: number;
  agree: Row[];
  clash: Row[];
  hard: number;
  sharp: number;
}

/** score.js compare(): every person against these answers, in the data's order. */
function compareAll(answers: Record<string, number>, shrink = SHRINK): Compared[] {
  return PEOPLE_KEYS.map(key => {
    const cells = PEOPLE[key]!.cells;
    let sum = 0, n = 0;
    const agree: Row[] = [], clash: Row[] = [];
    STATEMENTS.forEach(s => {
      const a = answers[s.id], c = cells[s.id];
      if (!a || !c) return;
      const m = KINDRED.centre[s.id] || [0, 0];
      const w = (a - shrink * m[0]) * (c.v - shrink * m[1]);
      sum += w; n++;
      (a * c.v > 0 ? agree : clash).push({ id: s.id, a: a as Answer, v: c.v, raw: a * c.v, w });
    });
    agree.sort((x, y) => y.w - x.w || y.raw - x.raw);
    clash.sort((x, y) => x.w - y.w || x.raw - y.raw);
    const hard = clash.filter(x => x.raw <= -4).length;
    const sharp = clash.filter(x => x.raw <= -2).length;
    return { key, n, like: sum / (n + K), agree, clash, hard, sharp };
  });
}

/**
 * score.js result(), on answers keyed by statement id (-2..2; 0 or missing is "Not sure").
 * Exported for the engine test's parity check; pages use resultFor() through the registry.
 */
export function matchAnswers(answers: Record<string, number>) {
  const ranked = compareAll(answers).sort((x, y) => y.like - x.like);
  const all = ranked.filter(r => r.n >= MIN_SHARED);
  const kindred = all.find(r => r.hard < 2 && r.agree.length >= 3) || all[0] || null;
  const sparring = all.slice().reverse().find(r =>
    r !== kindred && r.clash.length > r.agree.length && r.sharp >= 2
  ) || null;
  return { kindred, sparring, ranked };
}

// ---------------------------------------------------------------- what the result shows

/** preview/app.js show() and cardLine(), on one result. */
function choose(
  answers: Record<string, number>,
  kindred: Compared,
  sparring: Compared | null,
  ranked: Compared[]
): KindredShow {
  const Kk = kindred.key, Sk = sparring?.key ?? null;
  let face: string | null = null;
  if (Sk) {
    const both = STATEMENTS.filter(s => {
      const x = answers[s.id], ck = PEOPLE[Kk]!.cells[s.id], cs = PEOPLE[Sk]!.cells[s.id];
      return x && Math.abs(x) === 2 && ck && cs && !ck.hide && !cs.hide && ck.v * cs.v < 0;
    });
    face = both.length ? both[0]!.id : null;
  }
  const kShown = kindred.agree.filter(shownFor(Kk));
  const alike = kShown.filter(x => x.id !== face).slice(0, 3).map(x => x.id);
  const pushBack = kindred.clash.filter(shownFor(Kk)).filter(x => x.raw <= -2 && x.id !== face)[0]?.id ?? null;
  const argue = sparring ? sparring.clash.filter(shownFor(Sk!)).filter(x => x.id !== face).slice(0, 3).map(x => x.id) : [];
  const agree = sparring ? sparring.agree.filter(shownFor(Sk!))[0]?.id ?? null : null;
  const also = ranked
    .filter(x => x.key !== Kk && x.key !== Sk && x.agree.length)
    .slice(0, 2)
    .map(x => ({ key: x.key, slug: PEOPLE[x.key]!.slug, on: x.agree.filter(shownFor(x.key))[0]?.id ?? null }));

  // The card's line: the first of the top four that is short enough, else the shortest of them.
  const four = kShown.slice(0, 4).map(x => ({ id: x.id, len: PEOPLE[Kk]!.cells[x.id]!.len ?? 0 }));
  const fit = four.filter(c => c.len <= CARD_LINE_MAX);
  const card = (fit[0] ?? four.slice().sort((a, b) => a.len - b.len)[0])?.id ?? null;

  return {
    alike, pushBack, face, argue, agree, also, card,
    cardTopics: kShown.slice(0, 3).map(x => x.id),
    sparringTopics: sparring ? sparring.clash.filter(shownFor(Sk!)).slice(0, 3).map(x => x.id) : []
  };
}

// ---------------------------------------------------------------- values, answers, the view

function codecFor(quiz: Quiz) {
  return makeCodec(quiz.config.radix ?? 5, quiz.groups.length, quiz.codePrefix ?? '');
}

/** A value per group (0, 25, 50, 75, 100) as an answer (-2 .. 2). */
const answerOf = (value: number | undefined): Answer =>
  (Math.max(0, Math.min(4, Math.round((value ?? 50) / 25))) - 2) as Answer;

/** The answers a set of values stands for, keyed by statement id (the groups' keys). */
export function answersFromValues(quiz: Quiz, values: number[]): Record<string, Answer> {
  const out: Record<string, Answer> = {};
  quiz.groups.forEach((g, i) => { out[g.key] = answerOf(values[i]); });
  return out;
}

const person = (c: Compared): KindredPerson => {
  const p = PEOPLE[c.key]!;
  const cell = ({ id, a, v }: Row): KindredCell => ({ id, a, v });
  return {
    key: c.key,
    slug: p.slug,
    name: p.name,
    short: p.short,
    she: p.she,
    // For ordering only. A likeness is never printed against a person (hideOutcomeScore).
    score: Math.round(c.like * 1000) / 1000,
    shared: c.n,
    agree: c.agree.map(cell),
    clash: c.clash.map(cell)
  };
};

function view(quiz: Quiz, values: number[]): KindredView {
  const answers = answersFromValues(quiz, values);
  const code = codecFor(quiz).encode(values);
  const r = matchAnswers(answers);
  const ranked = r.ranked.map(person);
  const byKey = new Map(ranked.map(p => [p.key, p]));
  const base = { quizSlug: quiz.slug, code, answers, ranked, rows: [] as [] };

  if (!r.kindred) {
    const headline = 'Not enough to go on';
    return {
      ...base,
      shape: 'kindred',
      state: 'thin',
      named: [],
      headline,
      headlineParts: [{ text: headline, side: 'centre' }],
      summary: 'Nearly every answer was Not sure, so no one can be matched.',
      kindred: null,
      sparring: null,
      show: null
    };
  }

  const kindred = byKey.get(r.kindred.key)!;
  const sparring = r.sparring ? byKey.get(r.sparring.key)! : null;
  return {
    ...base,
    shape: 'kindred',
    state: 'matched',
    named: sparring ? [kindred.slug, sparring.slug] : [kindred.slug],
    headline: kindred.name,
    headlineParts: [{ text: kindred.name, side: 'centre' }],
    // Read on /me/ under the name, and as the result page's description. Neither "you" nor "they".
    summary: 'Kindred spirit in the early Church.' + (sparring ? ` Sparring partner: ${sparring.name}.` : ''),
    kindred,
    sparring,
    show: choose(answers, r.kindred, r.sparring, r.ranked)
  };
}

export const kindred: ScoringStrategy = {
  id: 'kindred',
  shape: 'kindred',
  /** A value per statement: (answer + 2) x 25, so "Not sure" and an unanswered statement are both 50. */
  score(quiz: Quiz, sheet: Sheet): number[] {
    const values = quiz.groups.map(() => 50);
    quiz.items.forEach((item, i) => {
      const a = sheet[i];
      values[item.group] = ((a ?? 0) + 2) * 25;
    });
    return values;
  },
  result: view,
  encode(quiz, values) {
    return codecFor(quiz).encode(values);
  },
  decode(quiz, code) {
    return codecFor(quiz).decode(String(code ?? '').toUpperCase());
  },
  /*
   * The title, the kindred spirit with their dates, the sparring partner, the link. Nothing about
   * how the person answered, and no number.
   */
  shareText(quiz, values, origin) {
    const v = view(quiz, values);
    const lines = [quiz.shareTitle];
    if (v.kindred) {
      lines.push(`${v.kindred.name}, ${PEOPLE[v.kindred.key]!.dates}`);
      if (v.sparring) lines.push(`Would argue with me: ${v.sparring.name}`);
    } else {
      lines.push('Not enough answers to name one.');
    }
    lines.push(`${origin}/r/${quiz.slug}/${v.code}`);
    return lines.join('\n');
  }
};
