/**
 * A reading: the third result shape, for "Which Psalm are you living right now?".
 *
 * Nothing here is a measurement. Seven even-handed questions (each running from hard,
 * through neutral, to good) and a few follow-ups, asked only when an answer calls for them,
 * are matched to ONE situation St Athanasius named in his Letter to Marcellinus, and his
 * advice for that situation is a psalm. Every situation is his: its `need` is his defining
 * condition, so a result is only ever offered to someone whose own answers meet it, and the
 * person confirms it ("Does this sound like you?") before they see it. "Not quite" offers
 * the next; after three, the runner says plainly that the letter does not name their
 * situation and offers the psalm he gave for what it is doing to them.
 *
 * The rules are data: src/data/which-psalm.json, generated by scripts/build-psalm-data.mjs
 * from design/quiz-ideas/psalm/ (model.mjs and its tree.json), where the questions were
 * tested on 150 simulated people and every situation was read in the Greek. The same
 * arithmetic ran in the owner's tap-through preview (design/quiz-ideas/psalm/score.js).
 *
 * The result code carries the SITUATION, never the answers: a shared link says "Psalm 3"
 * and nothing about how the person answered. It is 'PS' plus the situation's key without
 * its P (P42S -> PS42S), so a live code can never change meaning while its key exists.
 */
import data from '../../data/which-psalm.json';
import type { Quiz, ReadingView, ScoringStrategy } from '../engine/types';

export type Answers = Record<string, string | string[]>;
export type Condition = Record<string, string[]>;

export interface Question {
  id: string;
  q: string;
  options: [string, string][];
  /** Up to this many picks; absent means one. */
  max?: number;
  /** Laid out as a grid of single words, or of short phrases. */
  words?: boolean;
  short?: boolean;
  /** Follow-ups only: asked when any one of these is met. */
  when?: Condition[];
}

export interface Situation {
  psalm: number;
  /** A result that is a set of psalms (the Songs of Ascents); `psalm` leads it. */
  set?: number[];
  /** The other psalms Athanasius named for the same situation ("116:1-9" where he means part). */
  also: Array<number | string>;
  /** Section of the Letter to Marcellinus. */
  sec: string;
  /** His situation in plain words, shown as "Does this sound like you?". */
  seen: string;
  /** His advice, paraphrased from the Greek. */
  reason: string;
  /** The verse that names the situation, and the verse where the psalm turns (BSB refs). */
  names: string;
  turn: string | null;
  /** The first line that curses an enemy, with the note printed under the psalm. */
  hard?: string;
  hardNote?: string;
  /** A sentence that goes with this result wherever it is shown. */
  note?: string;
  /** A line that could wound someone in a particular situation, and the note that goes with it. */
  lineNote?: { ref: string; text: string; when?: Condition };
  need: Condition[];
  like: Condition;
}

/** A browsing group: how a reader walks the situations (the quiz page, /psalm/, "Close to this"). */
export interface SituationGroup {
  /** The anchor on /psalm/ (#people-against-you). */
  id: string;
  title: string;
  /** Situation keys, in the order they are listed. */
  ids: string[];
}

interface ReadingData {
  weights: Record<string, number>;
  core: Question[];
  follow: Question[];
  outcomes: Record<string, Situation>;
  groups: SituationGroup[];
  notes: Record<string, string>;
  none: { lead: string; options: [string, string][] };
  full: Record<string, { story: Array<{ t?: string; q?: string; ref?: string }>; own?: string; night?: string }>;
}

export const READING = data as unknown as ReadingData;
export const SITUATIONS = Object.keys(READING.outcomes);
/** Seven groups running from hard to good, as the questions do. Every situation is in exactly one. */
export const GROUPS = READING.groups;

/** The group a situation is listed under. */
export function groupOf(id: string): SituationGroup {
  const g = GROUPS.find(x => x.ids.includes(id));
  if (!g) throw new Error(`reading: situation ${id} is in no group`);
  return g;
}

/**
 * The page a situation's psalm lives on, and what to call it in a list. The Songs of Ascents
 * are one piece of advice for fifteen psalms; the list names all fifteen and opens on the first.
 */
export function psalmLinkFor(id: string): { href: string; label: string; short: string } {
  const o = READING.outcomes[id]!;
  if (o.set) {
    const first = Math.min(...o.set), last = Math.max(...o.set);
    return { href: `/psalm/${first}/`, label: `Psalms ${first}–${last}`, short: `${first}–${last}` };
  }
  return { href: `/psalm/${o.psalm}/`, label: `Psalm ${o.psalm}`, short: String(o.psalm) };
}

export function picks(v: string | string[] | undefined): string[] {
  return v === undefined ? [] : Array.isArray(v) ? v : [v];
}

export function meets(cond: Condition, a: Answers): boolean {
  return Object.entries(cond).every(([k, vals]) => picks(a[k]).some(x => vals.includes(x)));
}

/** Follow-ups whose condition the answers so far meet, in order, not yet answered. */
export function pending(a: Answers): Question[] {
  return READING.follow.filter(f => a[f.id] === undefined && (f.when ?? []).some(w => meets(w, a)));
}

/**
 * The next question, or null when the answers are complete. A follow-up is asked the moment
 * an answer calls for it, straight after that answer (the owner, 2026-09-23: "Who are they,
 * mostly?" arriving three questions after the people question came "out of nowhere").
 */
export function nextQuestion(a: Answers): Question | null {
  return pending(a)[0] ?? READING.core.find(q => a[q.id] === undefined) ?? null;
}

/**
 * The answer that called for a follow-up, as [question id, option key], so the screen can
 * say "You said: …" when the follow-up cannot sit right after it.
 */
export function trigger(a: Answers, f: Question): [string, string] | null {
  const w = (f.when ?? []).find(c => meets(c, a));
  if (!w) return null;
  const order = [...READING.core, ...READING.follow].map(q => q.id);
  const k = Object.keys(w).sort((x, y) => order.indexOf(x) - order.indexOf(y))[0]!;
  const v = picks(a[k]).find(x => w[k]!.includes(x));
  return v ? [k, v] : null;
}

/**
 * Situations the answers meet, best first. Each need facet met scores its weight (a direct
 * follow-up answer and the sentence a person would say to God count most; broad feeling
 * words least), each like facet one; ties keep the data's order.
 */
export function rank(a: Answers): Array<{ id: string; score: number }> {
  const w = READING.weights;
  const out: Array<{ id: string; score: number; order: number }> = [];
  SITUATIONS.forEach((id, order) => {
    const o = READING.outcomes[id]!;
    const hit = o.need.find(n => meets(n, a));
    if (!hit) return;
    const likes = Object.entries(o.like).filter(([k, vals]) => picks(a[k]).some(x => vals.includes(x))).length;
    const needScore = Object.keys(hit).reduce((n, k) => n + (w[k] ?? w.default ?? 2), 0);
    out.push({ id, score: needScore + likes, order });
  });
  return out.sort((x, y) => y.score - x.score || x.order - y.order).map(({ id, score }) => ({ id, score }));
}

/** The text of one option, for "You said" and the answers behind a result. */
export function optionText(qid: string, key: string): string {
  const q = [...READING.core, ...READING.follow].find(x => x.id === qid);
  return q?.options.find(o => o[0] === key)?.[1] ?? '';
}

export const codeFor = (id: string) => 'PS' + id.slice(1);

export function situationFor(code: string): string | null {
  const up = code.toUpperCase();
  if (!/^PS\d{1,3}[A-Z]?$/.test(up)) return null;
  const id = 'P' + up.slice(2);
  return READING.outcomes[id] ? id : null;
}

/** "Psalm 3", or "the Songs of Ascents" for the one result that is a set. */
export function titleOf(id: string): string {
  const o = READING.outcomes[id]!;
  return o.set ? 'The Songs of Ascents' : `Psalm ${o.psalm}`;
}

/**
 * Athanasius numbered the psalms from the Greek Bible. Orthodox readers, and Catholics with
 * older books, will look for his number; English Bibles use the Hebrew one.
 */
export function greekNumber(n: number): string {
  if (n <= 8 || n >= 148) return String(n);
  if (n <= 10) return '9';
  if (n <= 113) return String(n - 1);
  if (n <= 115) return '113';
  if (n === 116) return '114 and 115';
  if (n <= 146) return String(n - 1);
  return '146 and 147';
}

function view(quiz: Quiz, values: number[]): ReadingView {
  const id = SITUATIONS[values[0] ?? -1];
  if (!id) throw new Error(`reading: no situation at ${values[0]}`);
  const o = READING.outcomes[id]!;
  const headline = titleOf(id);
  return {
    shape: 'reading',
    state: 'clear',
    quizSlug: quiz.slug,
    code: codeFor(id),
    situation: id,
    psalm: o.psalm,
    named: [String(o.psalm)],
    headline,
    headlineParts: [{ text: headline, side: 'centre' }],
    summary: o.seen,
    ranked: [],
    rows: []
  };
}

export const reading: ScoringStrategy = {
  id: 'reading',
  shape: 'reading',
  score() {
    throw new Error('reading: this quiz is matched by its own runner (rank and the check step), not scored from a sheet');
  },
  result: view,
  encode(_quiz, values) {
    const id = SITUATIONS[values[0] ?? -1];
    if (!id) throw new Error(`reading: no situation at ${values[0]}`);
    return codeFor(id);
  },
  decode(_quiz, code) {
    const id = situationFor(code);
    return id ? [SITUATIONS.indexOf(id)] : null;
  },
  /*
   * The title, the psalm, the link: nothing about how the person answered, and not the
   * situation line either, because a share text is posted without the person there to say
   * it was theirs. Whoever follows the link reads the rest on the page.
   */
  shareText(quiz, values, origin) {
    const v = view(quiz, values);
    return [quiz.shareTitle, v.headline, `${origin}/r/${quiz.slug}/${v.code}`].join('\n');
  }
};
